[test]
levels = ["syntax", "javascript", "install", "registration", "instantiation", "execution"]
publish = true

[test.workflows]
cpu = ["merge_splats", "gaussian_analysis", "rotate_splats", "spectate"]
cuda = []

[test.platforms]
platforms = ["linux", "macos", "windows", "windows_portable"]
