[cuda]
packages = ["gsplat"]

[dependencies]
# Numerical / image staples.
numpy = "*"
pillow = "*"
av = "*"

[pypi-dependencies]
plyfile = ">=1.0.0"
aiohttp = "*"
nanogs = { git = "https://github.com/saliteta/NanoGS.git" }
packaging = "*"
psutil = "*"
rich = "*"
safetensors = "*"
scikit-learn = "*"